interledger/docs-styleguide

.github/workflows/deploy.yml, .github/workflows/test-build.yml, README.md, astro.config.mjs, src/content/docs/components/mermaidwrapper.mdx, src/content/docs/index.mdx
This PR updates the README and adds documentation for site building.
=> chore: update readme and docs

package.json
This PR bumps the site dependencies to the latest versions.
This will also let us see if the Mermaid issue is affecting this particular deployment environment because they updated again =_=
=> chore: bump site dependencies

astro.config.mjs, package.json
This PR adds expressive code style overrides to the astro configuration such that our CodeBlock components still look nice.
Starlight 0.13.0 finally shipped their expressive code integration (see https://github.com/withastro/starlight/releases/tag/%40astrojs%2Fstarlight%400.13.0), there are some styling changes that need to be made to our current CodeBlock component.
=> feat: add expressive code config

.github/workflows/deploy.yml, .github/workflows/test-build.yml, astro.config.mjs, package.json, src/content/docs/content/markdown.mdx, src/content/docs/shared/mermaid.mdx, src/content/docs/shared/mermaidwrapper.mdx
This PR updates our configuration and Mermaid diagram implementation.
Closes #23
=> refactor: update mermaid implementation

package.json, src/content/docs/index.mdx
This PR bumps dependencies to latest versions and fixes the Stylish Header example.
=> chore: bump dependencies to latest version

package.json
Discovered another bug with Mermaid diagrams so docs-design-system was updated again.
=> chore: update docs-design-system to latest

src/content/docs/shared/disclosure.mdx
=> docs: fix typo in disclosure style

src/content/docs/classes/img-outline.mdx, src/content/docs/content/global.mdx, src/content/docs/content/interledger.mdx, src/content/docs/content/markdown.mdx, src/content/docs/content/openpayments.mdx, src/content/docs/content/rafiki.mdx, src/content/docs/content/webmonetization.mdx, src/content/docs/index.mdx, src/content/docs/oppm/chunkedsnippet.mdx, src/content/docs/oppm/fullsnippet.mdx, src/content/docs/shared/codeblock.mdx, src/content/docs/shared/disclosure.mdx, src/content/docs/shared/hidden.mdx, src/content/docs/shared/largeimg.mdx, src/content/docs/shared/linkout.mdx, src/content/docs/shared/mermaid.mdx, src/content/docs/shared/mermaidwrapper.mdx, src/content/docs/shared/stylishheader.mdx, src/content/docs/shared/tooltip.mdx, src/content/docs/webm/browsercompat.mdx, src/content/docs/webm/specification.mdx
=> docs: random updates

src/content/docs/webm/browsercompat.mdx, src/content/docs/webm/specification.mdx
=> docs: spec and browsercompat comp fixes

package.json
This PR bumps our docs design system library to the latest version for bug fixes.
=> chore: update dds dependency

astro.config.mjs, package.json, src/content/docs/classes/img-outline.mdx, src/content/docs/classes/max-width.mdx, src/content/docs/index.mdx, src/content/docs/shared/mermaid.mdx
This PR bumps dds to the latest version and updates the component examples to reflect so
=> chore: bump dependencies to latest version and update components

src/content/docs/content/rafiki.mdx, src/content/docs/shared/removeoverview.mdx
=> rafiki and component updates

src/content/docs/shared/linkout.mdx
=> add build error info to linkout

astro.config.mjs, package.json, src/content/docs/content/markdown.mdx
Adds starlight links validator to site.
=> feat: add starlight links validator

astro.config.mjs, src/content/docs/classes/img-outline.mdx
=> docs: style description update

package.json
=> chore: dependency updates

vale/docStyles/Contractions.yml, vale/docStyles/Headings.yml, vale/docStyles/SentenceLength.yml, vale/docStyles/Spacing.yml, vale/docStyles/URLFormat.yml
=> adding new style files

.github/workflows/deploy.yml
This PR resolves the deployment issue by upgrading the upload-pages-artifact in the deployment workflow
=> fix: upgrade upload-pages-artifact

.github/workflows/deploy.yml
This PR upgrades deploy-action, hopefully we can deploy now =_=
=> fix: upgrade deploy-action

package-lock.json, src/content/docs/content/api.mdx
Updating the style guide to include the work that was done in https://github.com/interledger/rafiki/issues/3090
There is a placeholder section for REST APIs that will be completed this year as well.
=> docs: adding API style guide

vale/config/vocabularies/ilf/accept.txt
added additional words to vocab accept list
=> docs: accept.txt

src/components/docs/EmphasisText.astro, src/content/docs/webm/emphasistext.mdx
=> add page for new component

vale/docStyles/Nonwords.yml, vale/docStyles/Plurals.yml, vale/docStyles/Spelling.yml, vale/docStyles/Units.yml
=> docs: new vale styles

vale/config/vocabularies/ilf/accept.txt, vale/docStyles/Acronyms.yml
=> more style updates

vale/config/vocabularies/ilf/accept.txt, vale/docStyles/Acronyms.yml
=> style updates

vale/docStyles/Wordiness.yml
=> update wordiness file

vale/config/vocabularies/ilf/accept.txt
=> docs: add terms to vocab
